DROP VIEW IF EXISTS "Gebäude" CASCADE;
CREATE VIEW "Gebäude" AS
SELECT "id"                                       AS "ID",
       "street"                                   AS "Straße",
       "housenumber"                              AS "Hausnummer",
       "postcode"                                 AS "PLZ",
       "city"                                     AS "Ort",
       "type"                                     AS "Gebäudetyp",
       "yearOfConstruction"                       AS "Baujahr",
       "groupname"                                AS "Gebäudegruppe",
       "roof"                                     AS "Dachform",
       "floors"                                   AS "Etagen",
       ROUND("floorArea")                         AS "Grundfläche (m²)",
       ROUND("energyReferenceArea")               AS "Energiebezugsfläche (m²)",
       ROUND("livingArea")                        AS "Beheizte Wohnfläche (m²)",
       ROUND("wallAreaPerFloor")                  AS "Wandfläche je Etage (m²)",
       ROUND("wallArea")                          AS "Wandfläche gesamt (m²)",
       ROUND("roofArea")                          AS "Dachfläche (m²)",
       ROUND("surface")                           AS "Hüllfläche (m²)",
       ROUND("volumeLivingArea")                  AS "Volumen Wohnfläche (m³)",
       ROUND("transmissionSurface" / 1000)        AS "Transmissionswärmeverlust Hüllfläche (kW)",
       ROUND("transmission" / 1000)               AS "Transmissionswärmeverlust (kW)",
       ROUND("ventilationHeatLoss" / 1000)        AS "Lüftungswärmeverlust (kW)",
       ROUND("ventilationHeatLossComplex" / 1000) AS "Lüftungswärmeverlust komplex (kW)",
       ROUND("powerHeating" / 1000)               AS "Leistungsbedarf Heizung (kW)",
       ROUND("powerHotWater" / 1000)              AS "Leistungsbedarf Warmwasser (kW)",
       ROUND("demandHeating" / 1000)              AS "Wärmebedarf Heizung (kWh/a)",
       ROUND("demandHotWater" / 1000)             AS "Wärmebedarf Warmwasser (kWh/a)",
       ROUND("fullLoadHours")                     AS "Volllaststunden",
       "geometry"
FROM building;