DROP VIEW IF EXISTS "Rohrleitungen" CASCADE;
CREATE VIEW "Rohrleitungen" AS
SELECT "id"                         AS "ID",
       "location"                   AS "Art",
       "startPointId"               AS "Startpunkt",
       "endPointId"                 AS "Endpunkt",
       "length"                     AS "Länge (m)",
       "initialMassFlowRate"        AS "Massenstrom initial (kg/s)",
       "initialDiameterFlow"        AS "Rohrdurchmesser initial VL (mm)",
       "initialTypeFlow"            AS "Rohrtyp initial VL",
       "initialNominalSizeFlow"     AS "Nennweite initial VL (DN)",
       "initialInsulationFlow"      AS "Dämmstärketyp initial VL",
       "initialDiameterReturn"      AS "Rohrdurchmesser initial RL (mm)",
       "initialTypeReturn"          AS "Rohrtyp initial RL",
       "initialNominalSizeReturn"   AS "Nennweite initial RL (DN)",
       "initialInsulationReturn"    AS "Dämmstärketyp initial RL",
       "massFlowRate"               AS "Massenstrom (kg/s)",
       "typeFlow"                   AS "Rohrtyp VL",
       "nominalSizeFlow"            AS "Nennweite VL (DN)",
       "insulationFlow"             AS "Dämmstärketyp VL",
       "diameterFlow"               AS "Rohrdurchmesser VL (mm)",
       "flowVelocityFlow"           AS "Strömungsgeschwindigkeit VL (m/s)",
       "reynoldFlow"                AS "Reynoldszahl VL",
       "lambdaFlow"                 AS "Lambda VL",
       "pressureLossFlow"           AS "Druckverlust VL (Pa)",
       "specificPressureLossFlow"   AS "spez. Druckverlust VL (Pa/m)",
       "typeReturn"                 AS "Rohrtyp RL",
       "nominalSizeReturn"          AS "Nennweite RL (DN)",
       "insulationReturn"           AS "Dämmstärketyp RL",
       "diameterReturn"             AS "Rohrdurchmesser RL (mm)",
       "flowVelocityReturn"         AS "Strömungsgeschwindigkeit RL (m/s)",
       "reynoldReturn"              AS "Reynoldszahl RL",
       "lambdaReturn"               AS "Lambda RL",
       "pressureLossReturn"         AS "Druckverlust RL (Pa)",
       "specificPressureLossReturn" AS "spez. Druckverlust RL (Pa/m)",
       "heatLossWinter"             AS "Leistungsverlust Winter (W)",
       "heatLossSummer"             AS "Leistungsverlust Sommer (W)",
       "specificCostsFlow"          AS "spez. Kosten VL (€/m)",
       "specificCostsReturn"        AS "spez. Kosten RL (€/m)",
       "costsFlow"                  AS "Kosten VL (€)",
       "costsReturn"                AS "Kosten RL (€)",
       "geometry"
FROM pipe;