DROP VIEW IF EXISTS "Rohrleitungen";
CREATE VIEW "Rohrleitungen" AS
SELECT "id"                         AS "ID",
       "startPointId"               AS "Startpunkt",
       "endPointId"                 AS "Endpunkt",
       "length"                     AS "Länge (m)",
       "massFlowRate"               AS "Massenstrom (kg/s)",
       "initialDiameterFlow"        AS "Rohrdurchmesser initial VL (mm)",
       "initialTypeFlow"            AS "Rohrtyp initial VL",
       "initialNominalSizeFlow"     AS "Nennweite initial VL (DN)",
       "initialInsulationFlow"      AS "Dämmstärketyp initial VL",
       "initialDiameterReturn"      AS "Rohrdurchmesser initial RL (mm)",
       "initialTypeReturn"          AS "Rohrtyp initial RL",
       "initialNominalSizeReturn"   AS "Nennweite initial RL (DN)",
       "initialInsulationReturn"    AS "Dämmstärketyp initial RL",
       "typeFlow"                   AS "Rohrtyp VL",
       "nominalSizeFlow"            AS "Nennweite VL (DN)",
       "insulationFlow"             AS "Dämmstärketyp VL",
       "diameterFlow"               AS "Rohrdurchmesser VL (mm)",
       "flowVelocityFlow"           AS "Strömungsgeschwindigkeit VL (m/s)",
       "reynoldFlow"                AS "Reynoldszahl VL",
       "lambdaFlow"                 AS "Lambda VL",
       "pressureLossFlow"           AS "Druckverlust VL (Pa)",
       "specificPressureLossFlow"   AS "spez. Druckverlust VL (Pa/m)",
       "typeReturn"                 AS "Rohrtyp RL",
       "nominalSizeReturn"          AS "Nennweite RL (DN)",
       "insulationReturn"           AS "Dämmstärketyp RL",
       "diameterReturn"             AS "Rohrdurchmesser RL (mm)",
       "flowVelocityReturn"         AS "Strömungsgeschwindigkeit RL (m/s)",
       "reynoldReturn"              AS "Reynoldszahl RL",
       "lambdaReturn"               AS "Lambda RL",
       "pressureLossReturn"         AS "Druckverlust RL (Pa)",
       "specificPressureLossReturn" AS "spez. Druckverlust RL (Pa/m)",
       "heatLossWinter"             AS "Wärmeverlust Winter (W)",
       "specificHeatLossWinter"     AS "spez. Wärmeverlust Winter (W/m)",
       "heatLossSummer"             AS "Wärmeverlust Sommer (W)",
       "specificHeatLossSummer"     AS "spez. Wärmeverlust Sommer (W/m)",
       "geometry"
FROM pipe;