DROP VIEW IF EXISTS public.building_data;
CREATE VIEW public.building_data AS SELECT
    "id" AS "ID",
	"street" AS "Straße",
	"housenumber" AS "Hausnummer",
	"postcode" AS "PLZ",
	"city" AS "Ort",
	"type" AS "Gebäudetyp",
	"year_of_construction" AS "Baujahr",
	"groupname" AS "Gebäudegruppe",
	"roof" AS "Dachform",
	"floors" AS "Etagen",
	"groundAreaQM" AS "Grundfläche (m²)",
	"energyReferenceAreaQM" AS "Energiebezugsfläche (m²)",
	"livingAreaQM" AS "Beheizte Wohnfläche (m²)",
	"wallAreaPerFloorQM" AS "Wandfläche je Etage (m²)",
	"wallAreaQM" AS "Wandfläche gesamt (m²)",
	"roofAreaQM" AS "Dachfläche (m²)",
	"surfaceQM" AS "Hüllfläche (m²)",
	"volumeLivingAreaCBM" AS "Volumen Wohnfläche (m³)",
	"transmissionSurfaceW" AS "Transmissionswärmeverlust Hüllfläche (W)",
	"transmissionW" AS "Transmissionswärmeverlust (W)",
	"ventilationHeatLossW" AS "Lüftungswärmeverlust (W)",
	"ventilationHeatLossComplexW" AS "Lüftungswärmeverlust komplex (W)",
	"powerHeatingW" AS "Leistungsbedarf Heizung (W)",
	"powerHotWaterW" AS "Leistungsbedarf Warmwasser (W)",
	"demandHeatingKWH" AS "Wärmebedarf Heizung (kWh/a)",
	"demandHotWaterKWH" AS "Wärmebedarf Warmwasser (kWh/a)",
	"fullLoadHours" AS "Volllaststunden",
	"geometry"
FROM public.building;